variables:
    BASE_IMAGE: python:3.7
    RELEASE: tor-nightly-master-buster
    # Without version, the default available in the Debian repository will be
    # installed.
    # Specifying which version starts with will install the highest that start
    # with that version.
    TOR: tor=*
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

image: $BASE_IMAGE

before_script:
  - "wget https://deb.torproject.org/torproject.org/\
    A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89.asc"
  - cat A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89.asc  | apt-key add -
  - echo deb [signed-by=A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89]
    http://deb.torproject.org/torproject.org $RELEASE
    main >> /etc/apt/sources.list
  - apt update -yqq
  - apt install -yqq $TOR
  - pip install tox
  - python --version
  - tor --version

after_script:
  - tox -e stats

python36tor035:
  variables:
    BASE_IMAGE: python:3.6
    RELEASE: tor-nightly-0.3.5.x-buster
    TOR: tor=0.3.5*
  image: $BASE_IMAGE
  script:
    - tox -e py36
    - tox -e integration

python36tor041:
  variables:
    BASE_IMAGE: python:3.6
    RELEASE: tor-nightly-0.4.1.x-buster
    TOR: tor=0.4.1*
  image: $BASE_IMAGE
  script:
  - tox -e py36
  - tox -e integration

python36tor042:
  variables:
    BASE_IMAGE: python:3.6
    RELEASE: tor-nightly-0.4.2.x-buster
    TOR: tor=0.4.2*
  image: $BASE_IMAGE
  script:
  - tox -e py36
  - tox -e integration

python36torstable:
  variables:
    BASE_IMAGE: python:3.6
    RELEASE: buster
    TOR: tor
  image: $BASE_IMAGE
  script:
  - tox -e py36
  - tox -e integration

python37:
  # This will overwrite the default before_script, so need to repeat the
  # commands
  before_script:
    - "wget https://deb.torproject.org/torproject.org/\
      A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89.asc"
    - cat A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89.asc  | apt-key add -
    - echo deb [signed-by=A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89]
      http://deb.torproject.org/torproject.org $RELEASE
      main >> /etc/apt/sources.list
    - apt update -yqq
    - apt install -yqq $TOR
    - pip install tox
    - python --version
    - tor --version
    # To build the docs
    - apt install -yqq texlive-latex-extra
    - apt install -yqq dvipng
  image: $BASE_IMAGE
  script:
  - tox -e inst
  - tox -e setup
  - tox -e py37
  - tox -e integration
  - tox -e lint
  - tox -e doc

python38:
  variables:
    BASE_IMAGE: python:3.8
  image: $BASE_IMAGE
  script:
  - tox -e py38
  - tox -e integration

python39:
  variables:
    BASE_IMAGE: python:3.9-rc-buster
  image: $BASE_IMAGE
  script:
  - tox -e py39
  - tox -e integration
  allow_failure: true
