version: '2.2'
services:
  sbws-relay:
    image: ghcr.io/anyone-protocol/ator-protocol-dev:latest
    restart: always
    expose:
      - "9051"
    volumes:
      - ./data/:/var/lib/anon
      - ./relay/anonrc:/etc/anon/anonrc
    networks:
      local:
        ipv4_address: 172.18.0.2
  sbws-scanner:
    image: sbws-scanner
    restart: always
    depends_on:
      - sbws-relay
    volumes:
      - ./scanner/.sbws.ini:/root/.sbws.ini
      - ./data:/root/.sbws
    environment:
      INTERVAL_MINUTES: 5
    networks:
      local:
        ipv4_address: 172.18.0.3

networks:
  local:
    ipam:
      driver: default
      config:
        - subnet: "172.18.0.0/24"
          gateway: "172.18.0.1"
