name: DEV - Build and Deploy

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Build and push
        uses: ./.github/actions/build-and-push
        with:
          docker-username: ${{ github.actor }}
          docker-password: ${{ secrets.GITHUB_TOKEN }}
          docker-tag: ${{ github.sha }}
      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          environment: dev
          nomad-cacert: operations/admin-ui-ca.crt
          nomad-token: ${{ secrets.NOMAD_TOKEN_SBWS_DEPLOY }}
          nomad-addr: ${{ secrets.NOMAD_DEPLOY_ADDR }}
          docker-tag: ${{ github.sha }}
